#!/bin/bash
set -e


cd ../mathcat
py addmathcat4.py ../intent4/intent4.html > intent4.html
cd ../mathcat2
#cp  ../mathcat/intent4.html ../docs/intent4.html
py addmathcat4b.py ../mathcat/intent4.html > ../docs/intent4.html


