#!/bin/bash
set -e


mv '/c/users/davidc/Downloads/List of intent values (under development).zip' x2.zip \
   2> /dev/null || \
    echo "re-using download"

unzip -o x2.zip

echo "<html>" > in2.xml
sed -e 's/<br>/<br\/>/g' \
    -e 's/<link [^<>]*>//g' \
    -e 's/<meta [^<>]*>//g' \
    'Intent Core.html' >> in2.xml
echo "</html>" >> in2.xml


saxon10 -o:../mathcat/intent2.html in2.xml in2.xsl

cd ../mathcat
py addmathcat.py intent2.html > ../docs/intent2.html


