#!/bin/bash
set -e


mv '/c/users/davidc/Downloads/Notation which often needs intent in order to pronounce correctly in English.zip' x.zip \
   2> /dev/null || \
    echo "re-using download"

unzip -o x.zip

echo "<html>" > in.xml
sed -e 's/<br>/<br\/>/g' \
    -e 's/<link [^<>]*>//g' \
    -e 's/<meta [^<>]*>//g' \
    Sheet1.html >> in.xml
echo "</html>" >> in.xml


saxon10 -o:../mathcat/intent1.html in.xml in.xsl

cd ../mathcat
py addmathcat.py intent1.html > ../docs/intent1.html

grep -o 'intent="[^"]*' ../docs/intent1.html | \
     sed -e 's/intent="//' \
         -e 's/\$[a-zA-Z]*//g' \
	 -e 's/[(),][0-9]*//g' \
	 -e 's/@[a-z]*//g' \
	 | sort | uniq


